# Site settings
title: "dust-nib"
description: > 
  Hi! I'm nibnalin.<br>This is my corner of the internet, a dust-nib for my thoughts.

author: Nalin Bhardwaj
email: nalinbhardwaj@nibnalin.me
twitter_username: nibnalin
github_username: nalinbhardwaj

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nibnalin.me" # the base hostname & protocol for your site

# Build settings
include: [_pages]
markdown: kramdown
permalink: /dust-nib/:title.html

kramdown:
    math-engine: katex

sass:
    style: compressed

exclude: [vendor]

plugins:
  - jekyll-spaceship
